%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%   
%%   
%% THIS CODE WAS DYNAMICALLY GENERATED BY CAMeLOT    
%% Code generated at Mon Jul  6 14:39:51 2015
%% Generated by CAMeLOT version 0.1.0
%%   
%%   
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


addpath PATH FOR MATLAB CODE
startup
num_opt = 4
type_opt = {'eps_opt_weak', 'eps_opt_strong', 'eps_opt_chg', 'sig_opt_chg'}
F = @(x)cg_opt_func(x, num_opt, type_opt);

opt = bo_default_opt();
opt.dims = num_opt; 

opt.mins(1)  = 0.010;
opt.maxes(1) = 0.300;
opt.mins(2)  = 0.500;
opt.maxes(2) = 1.500;
opt.mins(3)  = 0.200;
opt.maxes(3) = 2.000;
opt.mins(4)  = 8.500;
opt.maxes(4) = 10.500;

opt.max_iters = 500;
opt.save_trace = true;

% run optimization
[ms,mv,T] = bayesopt(F,opt);

fprintf('\n**Optimization finished.\n');
fprintf('Minimum function value found in grid was \%f\n',mv);
fprintf('Point with minimum value was...\n');
disp(ms);
