## CAMeLOT V 0.1.2
## Coarse-grained simulations Aided by Machine Learning, Optimization and Training
## Pappu lab, Washington University in St. Louis
## Code written by Alex Holehouse based on original principles developed by Kiersten Ruff
## Copyright 2015 - 2019
##
echo "Removing autogenerated code from this directory..."
rm cg_opt_m.m
rm cg_opt.m
rm cg_opt_func.m
rm update_moltemplate.py
rm run_simulation.py
rm generate_nvt.py
echo "...DONE"
